### ISSUE TITLE
Just simple bug

### ISSUE THREAD

**Issue by Lordofdeaddread** [XtarsAgency/Arvtom#1]
It seems that when you pair both sets of the mods 

- zeridmuth a new beginning 
- arvtom : last descent 

It causes a bug in the mod Loader that causes the game to crash. This may be do to phone model, or updates [ unlikely as I have the latest version] 

I'm not sure what causes the system to fail to respond, but hope it can be patched soon.

**Comment by XtarsAgency** [comment]
Okay, we fixed some things. Please try to reinstall the mod now

**Comment by Lordofdeaddread** [comment]
It appears that the mod Loader refuses to run the files for it.

**Comment by XtarsAgency** [comment]
Yea, i still dont know about that, currently going through every files in the mod

**Comment by Lordofdeaddread** [comment]
Thanks. I've tried checking if maybe anything do to controllers was changed
or a core patch for the game came out and changed a few things.

**Comment by XtarsAgency** [comment]
Does it work now? It doesnt for me

**Comment by Lordofdeaddread** [comment]
Same. Not sure what's going on

**Comment by XtarsAgency** [comment]
Fixed

**Comment by Lordofdeaddread** [comment]
Oh boss.. you're gonna hate me. You really will. Seems your patch did
something else to the main mod

**Comment by XtarsAgency** [comment]
What is it?

**Comment by Lordofdeaddread** [comment]
For zeridmuth a new beginning seems that now there's a loading bug for it
where it says there's a " ] " where a key name was expected. Says to use
the key name or leave a whitespace where expected at 2:34

**Comment by XtarsAgency** [comment]
Just disable Zeridmuth because in there is a demo of Arvtom, just a demo, i might remove it sooner or later but i will keep it for now. Disable Zeridmuth, remember its lore connects doesnt mean its techtree connects too, its just those two planets appear on each mod. might rename
